#!/usr/bin/env python
import subprocess
import re

from urllib import request
url = "https://julialang.org/downloads/"
page = request.urlopen(url).read().decode('utf-8')

regex = re.compile(r'.*(https\:.*\/julia-.*-linux-x86_64.tar.gz).*')
dlurl = regex.findall(page)[0]
fname = url.strip('/').split('/')[-1]

subprocess.call(f'wget {url} -O ~/Downloads/{fname}',
                shell=True)

subprocess.call(f'tar -xf ~/Downloads/{fname} -C ~/Applications/',
                shell=True)

#**********************************************
# Install my packages
#**********************************************

#from Pkg.installed()
pkgdump = """
  "Distributions" => v"0.21.3"
  "Atom"          => v"0.11.2"
  "Gaston"        => v"0.10.0"
  "Juno"          => v"0.7.2"
  "IterTools"     => v"1.2.0"
  "ColorSchemes"  => v"3.5.0"
  "OffsetArrays"  => v"0.11.1"
  "DSP"           => v"0.6.0"
  "LaTeXStrings"  => v"1.0.3"
  "StatsBase"     => v"0.32.0"
  "Weave"         => v"0.9.1"
  "IJulia"        => v"1.20.0"
  "ImageMagick"   => v"0.7.5"
  "PGFPlots"      => v"3.1.3"
  "Plots"         => v"0.27.0"
  "Colors"        => v"0.9.6"
  "PyPlot"        => v"2.8.2"
  "jlpkg"         => v"1.1.1"
  "TikzPictures"  => v"3.0.5"
  "FFTW"          => v"1.0.1"
"""

import glob
from path import Path
juliabin = glob.glob(Path('~/Applications/julia-*/bin/julia').expanduser())[0]

def add_pkg(pkgname):
    subprocess.call(f'''{juliabin} -e 'using Pkg; Pkg.add("{pkgname}")' ''',
                    shell=True)


pkglist = [i.strip().strip('"').split('"')[0].strip() for i in pkgdump.split('\n') if i.strip()!='']
for pkg in pkglist:
    add_pkg(pkg)
    