#!/usr/bin/python3
import subprocess
import re

subprocess.call(f'sudo apt install inkscape', shell=True)

#install git and generate ssh key
subprocess.call(f'sudo apt install git', shell=True)
subprocess.call('git config --global user.name heetbeet', shell=True)
subprocess.call('git config --global user.email example@example.com', shell=True)
subprocess.call('cat /dev/zero | ssh-keygen -q -N ""', shell=True)


subprocess.call(f'sudo apt install guake', shell=True)
subprocess.call(f'sudo apt install xclip', shell=True)

#install all the get-install files
import os
files = [i for i in os.listdir() if i.startswith('get-install-') and not '-defaults' in i]
for file in files:
	subprocess.call(file, shell=True)
