#!/usr/bin/python3
import subprocess
import re

from urllib import request
url = "https://repo.continuum.io/archive/"
names = request.urlopen(url).read().decode('utf-8')

anaconda = re.compile(r'.*(Anaconda3-.*-Linux.*_64\.sh).*')
url = url+ anaconda.findall(names)[0]
name = url.strip('/').split('/')[-1]

subprocess.call(f'wget {url} -O ~/Downloads/{name}',
                shell=True)

subprocess.call(f'bash ~/Downloads/{name} -b',
                shell=True)