#!/usr/bin/env python
import subprocess
import os

url = 'https://github.com/scottkosty/install-tl-ubuntu/raw/master/install-tl-ubuntu'

fname = url.strip('/').split('/')[-1]

subprocess.call(f'wget {url} -O ~/Downloads/{fname} && chmod +x ~/Downloads/{fname}',
                shell=True)

subprocess.call(f'sudo ~/Downloads/{fname}',
	            cwd=os.path.expanduser('~/Downloads/'),
                shell=True)