#!/usr/bin/env python
import subprocess
import os
from path import Path

thisdir = Path(__file__).dirname().abspath()

thisdir.chdir()

print("Adding shortcut to /usr/share/nemo/actions/open-in-guake.nemo_action")


Path('~/Downloads/open-in-guake.nemo_action').expanduser().open('w').write(
"""[Nemo Action]
Active=true
Name=Open in Guake
Comment=Open "%f"
Exec=nohup guake -n -s --show --execute-command="cd '%F'; clear" >/dev/null 2>&1 &
Icon-Name=terminal
Selection=any
Extensions=any;
Quote=double
"""
)

subprocess.call(['sudo',
                 'cp',
                 Path('~/Downloads/open-in-guake.nemo_action').expanduser(),
                 '/usr/share/nemo/actions/open-in-guake.nemo_action'
                 ])
